version: '3'
services:
  composer:
    image: composer
    volumes:
      - .:/app
      - ~/.ssh:/root/.ssh
      - ~/.composer:/tmp
    command: install

  backend:
    image: craftcms/php-fpm:8.0
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          memory: 1024M
    logging:
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      PHP_UPLOAD_MAX_FILESIZE: 128M
      PHP_POST_MAX_SIZE: 128M
      PHP_MAX_INPUT_VARS: 10000
    depends_on:
      - mariadb
      - redis

  mariadb:
    image: mariadb
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql:delegated
    environment:
      MYSQL_DATABASE: craft
      MYSQL_USER: craft
      MYSQL_PASSWORD: craft
      MYSQL_ROOT_PASSWORD: root
    deploy:
      resources:
        limits:
          memory: 512M
    logging:
      options:
        max-size: "1m"
        max-file: "3"

  webserver:
    image: nginx:alpine
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    deploy:
      resources:
        limits:
          memory: 128M
    logging:
      options:
        max-size: "1m"
        max-file: "3"
    depends_on:
      - backend
      - console

  console:
    image: craftcms/cli:8.0
    volumes:
      - .:/app
    env_file: .env
    command: sh -c 'sleep 30 && ./craft queue/listen --verbose=1 --interactive=0 --isolate=1'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1024M
    logging:
      options:
        max-size: "1m"
        max-file: "3"
    depends_on:
      - mariadb
      - redis

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    deploy:
      resources:
        limits:
          memory: 128M
    logging:
      options:
        max-size: "1m"
        max-file: "3"

volumes:
  dbdata:
    driver: local
